### Users - SignUp
POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
    "username": "johdoe",
    "name": "John Doe",
    "email": "johndoe@email.com",
    "password": "xxxxxx"
}

### Users - Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "johdoe",
    "password": "xxxxxx"
}

### Users - Logout
POST http://localhost:3001/api/users/logout
