### Users - Profile
GET http://localhost:3001/api/users/profile/johndoe

### Users - SignUp
POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
    "username": "johdoe",
    "name": "John Doe",
    "email": "johndoe@email.com",
    "password": "xxxxxx"
}

### Users - Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "12345"
}

### Users - Logout
POST http://localhost:3001/api/users/logout

### User - Follow / Unfollow
POST http://localhost:3001/api/users/follow/67aa34f2a5e4719af99ac18b

### User - Update
POST http://localhost:3001/api/users/update/67a9e565c91abf0ff292207c
Content-Type: application/json

{
    "username": "johndoe"
}

### Posts - Create
POST http://localhost:3001/api/posts/create
Content-Type: application/json

{
    "postedBy": "67a9e565c91abf0ff292207c",
    "text": "this is my first post"
}

### Posts - Get Post
GET http://localhost:3001/api/posts/67acd59b1c884aa21ad911ed

### Posts - Delete
DELETE http://localhost:3001/api/posts/67acd1298023cf6f67b7fcab

### Posts - Like / Unlike
POST http://localhost:3001/api/posts/like/67acd59b1c884aa21ad911ed